name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv based on the config files in the working-directory
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run ty
        run: uv run ty check
      # https://docs.astral.sh/ruff/integrations/#github-actions
      - name: Run Ruff
        run: uv run ruff check --output-format=github .
      # - name: Run pytest
      #   run: uv run pytest tests/ -v
